#!/bin/sh

USER="wyona"
STARTCMD="/usr/local/home/wyona/build/jakarta-tomcat-4.0.4/bin/startup.sh"
STOPCMD="/usr/local/home/wyona/build/jakarta-tomcat-4.0.4/bin/shutdown.sh"


case "$1" in

start)
  echo "Starting Wyona-Tomcat"
  su - $USER $STARTCMD
  ;;
stop)
  echo "Stopping Wyona-Tomcat"
  su - $USER $STOPCMD
  ;;
*)
  echo "Usage: /etc/init.d/tomcatctl {start|stop}"
  exit 1
esac

