#! /bin/sh
# filename: skip-dummy-ns
#
# set path to your uzh publication (that is being patched) accordingly
find path/to/your/uzh/pub -type f -name 'xhtml-standard.xsl' -print | while read i
do
  sed 's/xmlns\:xsl=\"http\:\/\/www\.unizh\.ch\/dummy-ns\/\"//g' $i > $i.tmp && mv $i.tmp $i
done
